[tools]
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@openai/codex" = "latest"

python = "3.13"
uv = "latest"

usage = "latest"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true

[settings.python]
compile = false
