[tools]
"npm:ccstatusline" = "latest"

uv = "latest"

claude = "latest"
usage = "latest"

[tools."github:mono0x/git-default-branch"]
version = "latest"
bin = "git-default-branch"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
install_before = "3d"

[settings.pipx]
uvx = true

[settings.python]
compile = false
