[tools]
node = "24"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@dotenvx/dotenvx" = "latest"

python = "3.13"
uv = "latest"

usage = "latest"

[tools."github:mono0x/git-default-branch"]
version = "latest"
bin = "git-default-branch"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true

[settings.python]
compile = false
