[tools]
node = "24"
pnpm = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:ccstatusline" = "latest"

python = "3.13"
uv = "latest"

claude = "latest"
usage = "latest"

[tools."github:mono0x/git-default-branch"]
version = "latest"
bin = "git-default-branch"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
install_before = "3d"

[settings.pipx]
uvx = true

[settings.python]
compile = false

[settings.npm]
package_manager = "pnpm"
