name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
env:
  MISE_VERSION: 2025.11.8
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          submodules: recursive
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          version: ${{ env.MISE_VERSION }}
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
      - name: Copy install.sh to outside of the repository
        run: |
          cp ./install.sh /tmp/install.sh
      - name: Run test
        working-directory: /tmp
        run: |
          ./install.sh
          # Run script twice to test idempotency
          ./install.sh

  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          version: ${{ env.MISE_VERSION }}
      - name: Install dependencies
        run: sudo apt install -y zsh
      - name: Run test
        run: ./test/static.sh

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982 # v1.69.1
