name: CI
on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: recursive
      - uses: jdx/mise-action@9dc7d5dd454262207dea3ab5a06a3df6afc8ff26 # v3.4.1
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
      - name: Copy install.sh to outside of the repository
        run: |
          cp ./install.sh /tmp/install.sh
      - name: Run test
        working-directory: /tmp
        run: |
          ./install.sh
          # Run script twice to test idempotency
          ./install.sh

  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: jdx/mise-action@5ac50f778e26fac95da98d50503682459e86d566 # v3.2.0
      - name: Install dependencies
        run: sudo apt install -y zsh
      - name: Run test
        run: ./test/static.sh

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: reviewdog/action-actionlint@f00ad0691526c10be4021a91b2510f0a769b14d0 # v1.68.0
